# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "fiona"
        dependency-type: "direct"
      - dependency-name: "fsspec"
        dependency-type: "direct"
      - dependency-name: "pyproj"
        dependency-type: "direct"
      - dependency-name: "rasterio"
        dependency-type: "direct"
      - dependency-name: "shapely"
        dependency-type: "direct"
