---
process:
    name: hillshade
    input_files:
        - /home/ungarj/terrain/out/dem/
    output_folder: /home/ungarj/terrain/out/hillshade/
    profile: PNG_hillshade
    EPSG: 4326
    metatiling: 4
    parallel: 3
    debug: True
    create_vrt: False


required_process:
   name: tilify_raster
   input_files:
       - /home/ungarj/geodata/srtm30/srtm30.vrt
   output_folder: /home/ungarj/terrain/out/dem
   profile: GTiff
   EPSG: 4326
   metatiling: 1
   parallel: 3
   create_vrt: True
   debug: True